// This file is auto-generated by GitHub Actions
// DO NOT EDIT MANUALLY - Changes will be overwritten
// Generated from GitHub Issues with label 'maintenance'
// Last updated: 2025-10-19T09:00:22.519Z

import { MaintenanceConfig } from './types/config'

export const maintenances: MaintenanceConfig[] = [
  {
    title: 'Database Server Maintenance',
    body: `We will be performing database server maintenance including:
- Index optimization
- Security updates
- Performance tuning
Expected downtime: 4 hours
Contact: ops@example.com for urgent issues`,
    start: '2024-12-20T02:00:00+00:00',
    end: '2024-12-20T06:00:00+00:00',
    color: '#f97316',
    monitors: ["foo_monitor"],
  },
  {
    title: 'Network Infrastructure Upgrade',
    body: `Upgrading network infrastructure for improved reliability and performance.
This maintenance will be ongoing until further notice.
All services may experience intermittent connectivity issues.`,
    start: '2024-12-21T01:00:00+00:00',
    color: '#3b82f6',
    monitors: ["foo_monitor","test_tcp_monitor"],
  },
  {
    title: 'Emergency Security Patch',
    body: `Critical security patches are being applied immediately.
All systems are affected. Maintenance started immediately and will continue until patches are complete.`,
    color: '#ef4444',
  },
  {
    title: 'Routine System Cleanup',
    body: `Performing routine system cleanup and optimization tasks.
This is a low-priority maintenance with no expected service interruption.`,
    monitors: ["test_tcp_monitor"],
  },
]
