// This file is auto-generated by GitHub Actions
// DO NOT EDIT MANUALLY - Changes will be overwritten
// Generated from GitHub Issues with label 'maintenance'
// Last updated: 2025-10-19T09:14:42.755Z

import { MaintenanceConfig } from './types/config'

export const maintenances: MaintenanceConfig[] = [
  {
    title: 'Emergency Maintenance',
    body: `### Maintenance Description
### Instructions
\`\`\`markdown
**How to use this template:**
1. **Title**: Enter your maintenance title above
2. **Description**: Fill out the description above with maintenance details
3. **Labels**: After creating the issue, add monitor ID labels (e.g., \`foo_monitor\`, \`test_tcp_monitor\`)
4. **Keywords**: Use \` \` and \` keywords in the description for scheduling
**Monitor Labels:**
- \`foo_monitor\` - My API Monitor
- \`test_tcp_monitor\` - Example TCP Monitor
- No labels = affects all monitors
**Color Examples:**
- \` - Yellow (warning)
- \` - Blue (info)
- \` - Orange (caution)
- \` - Red (critical)
\`\`\``,
    start: '2025-10-19T09:10:58.489Z',
    end: '2025-12-19T09:10:58.489Z',
    color: 'red',
    monitors: ["foo_monitor"],
  },
]
