// This file is auto-generated by GitHub Actions
// DO NOT EDIT MANUALLY - Changes will be overwritten
// Generated from GitHub Issues with label 'maintenance'
// Last updated: 2025-10-19T09:16:27.192Z

import { MaintenanceConfig } from './types/config'

export const maintenances: MaintenanceConfig[] = [
  {
    title: 'Emergency Maintenance',
    body: `### Maintenance Description
We neeed to fix this`,
    start: '2025-10-19T09:10:58.489Z',
    end: '2025-12-19T09:10:58.489Z',
    color: 'red',
    monitors: ["foo_monitor"],
  },
]
